name: Cleanup Build Cache
permissions: {}

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Do a dry-run"
        required: true
        type: boolean
        default: true
      older_than:
        description: "Delete older then"
        required: true
        default: "30 days"

  schedule:
    - cron: "0 1 * * FRI"
      timezone: UTC

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Delete older than (Manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          package: rust-musl-buildcache
          dry-run: ${{ inputs.dry_run }}
          older-than: ${{ inputs.older_than }}

      - name: Delete older than 30 days (Scheduled)
        if: ${{ github.event_name == 'schedule' }}
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          package: rust-musl-buildcache
          dry-run: false
          older-than: 30 days

      - name: Delete older than (Manual) - Toolchain
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          package: musl-toolchain-buildcache
          dry-run: ${{ inputs.dry_run }}
          older-than: ${{ inputs.older_than }}

      - name: Delete older than 30 days (Scheduled) - Toolchain
        if: ${{ github.event_name == 'schedule' }}
        uses: dataaxiom/ghcr-cleanup-action@f092b48ba3b604b2a83690dc4b2bbb3392e1045f # v1.2.1
        with:
          package: musl-toolchain-buildcache
          dry-run: false
          older-than: 30 days
